const { m } = require('framer-motion');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#ffffff",
        secondary: "#0088cc",
        accent: "#e8f5ff",
        cards: "#f5f5f5",
        cards2: "#d3eaf7",
        cards3: "#ffffff",
        hoverbg: "#d1e9ff",
        headerCard: "#e6f2fb",
        energybar: "#0088cc",
        btn: "#0088cc",
        btn2: "#006699",
        btn3: "#004c7a",
        btn4: "#ffffff",
        taskicon: "#a0a0a0",
        divider: "#e0e0e0",
        borders: "#cfd8dc",
        borders2: "#b0bec5",
        accent2: "#b3e5fc",
        cardtext: "#212121",
        lime: "#c6ff00",
        dimtext: "#757575",
        divider2: "#cfd8dc",
        divider3: "#b0bec5",
        modal: "#f0f0f0",
      },
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
        Inter: ["'Inter', sans-serif"],
        outfit: ["'Outfit', sans-serif"],
        RobotoMono: ["'Roboto Mono', monospace"],
        PublicSans: ["'Public Sans', sans-serif"],
        Monserrat: ["'Montserrat', sans-serif"],
        Syne: ["'Syne', sans-serif"],
        Orkney: ["'Orkney', sans-serif"],
        Cerebri: ["'Cerebri Sans', sans-serif"],
      },
    },
    screens: {
      xs: "480px",
      ss: "600px",
      sm: "768px",
      ms: "1024px",
      md: "1140px",
      lg: "1200px",
      xl: "1700px",
    },
  },
  plugins: [require('tailwindcss')],
};
