name: Unzip File

on:
  push:
    paths:
      - '**/*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git user identity
        run: |
          git config --global user.name "hridoymcom"
          git config --global user.email "hridoymcom@gmail.com"

      - name: Unzip file
        run: |
          mkdir extracted_files
          unzip '*.zip' -d extracted_files/

      - name: Commit extracted files
        run: |
          git add extracted_files/*
          git commit -m "Unzipped files"
          git push
